/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as CreateRouteImport } from './routes/create'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as WorldRouteImport } from './routes/world'
import { Route as ApiPublicProductionSweepRouteImport } from './routes/api/public/production-sweep'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductionSweepRoute =
  ApiPublicProductionSweepRouteImport.update({
    id: '/api/public/production-sweep',
    path: '/api/public/production-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/create': typeof CreateRoute
  '/library': typeof LibraryRoute
  '/production': typeof ProductionRoute
  '/world': typeof WorldRoute
  '/api/public/production-sweep': typeof ApiPublicProductionSweepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/create': typeof CreateRoute
  '/library': typeof LibraryRoute
  '/production': typeof ProductionRoute
  '/world': typeof WorldRoute
  '/api/public/production-sweep': typeof ApiPublicProductionSweepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/create': typeof CreateRoute
  '/library': typeof LibraryRoute
  '/production': typeof ProductionRoute
  '/world': typeof WorldRoute
  '/api/public/production-sweep': typeof ApiPublicProductionSweepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/create'
    | '/library'
    | '/production'
    | '/world'
    | '/api/public/production-sweep'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/create'
    | '/library'
    | '/production'
    | '/world'
    | '/api/public/production-sweep'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/create'
    | '/library'
    | '/production'
    | '/world'
    | '/api/public/production-sweep'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  CreateRoute: typeof CreateRoute
  LibraryRoute: typeof LibraryRoute
  ProductionRoute: typeof ProductionRoute
  WorldRoute: typeof WorldRoute
  ApiPublicProductionSweepRoute: typeof ApiPublicProductionSweepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/production-sweep': {
      id: '/api/public/production-sweep'
      path: '/api/public/production-sweep'
      fullPath: '/api/public/production-sweep'
      preLoaderRoute: typeof ApiPublicProductionSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  CreateRoute: CreateRoute,
  LibraryRoute: LibraryRoute,
  ProductionRoute: ProductionRoute,
  WorldRoute: WorldRoute,
  ApiPublicProductionSweepRoute: ApiPublicProductionSweepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
